version: '3.7'

services:
    pgadmin:
        image: 'dpage/pgadmin4'
        container_name: 'pgAdmin'
        hostname: 'pgAdmin'
        environment:
          PGADMIN_DEFAULT_EMAIL: admin
          PGADMIN_DEFAULT_PASSWORD: admin
          PGADMIN_PORT: 5050
        networks:
          - data_default
        ports:
          - 5050:5050

    mongo-express:
        image: 'mongo-express'
        container_name: 'MongoExpress'
        hostname: 'MongoExpress'
        environment:
            - ME_CONFIG_MONGODB_SERVER=MongoDB
            - ME_CONFIG_MONGODB_ADMINUSERNAME=root
            - ME_CONFIG_MONGODB_ADMINPASSWORD=root
        networks:
            - data_default
        ports:
            - 8081:8081

    kibana:
        image: 'kibana:7.5.1'
        container_name: 'Kibana'
        hostname: 'Kibana'
        networks:
            - data_default
        ports:
            - 5601:5601

networks:
    data_default:
        name: 'data_default'
        driver: 'bridge'
