version: '3.7'

services:

  mongo:
    image: 'mongo'
    container_name: 'MongoDB'
    hostname: 'MongoDB'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - mongodb:/data/db
    networks:
      - data_default
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019

  mongo-express:
    image: 'mongo-express'
    container_name: 'MongoExpress'
    hostname: 'MongoExpress'
    environment:
      - ME_CONFIG_MONGODB_SERVER=MongoDB
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    networks:
      - data_default
    ports:
      - 8081:8081

  redis:
    image: 'bitnami/redis'
    container_name: 'Redis'
    hostname: 'Redis'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - data_default

  elasticsearch:
    image: 'elasticsearch:7.5.1'
    container_name: 'ElasticSearch'
    hostname: 'ElasticSearch'
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - data_default
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: 'kibana:7.5.1'
    container_name: 'Kibana'
    hostname: 'Kibana'
    networks:
      - data_default
    ports:
      - 5601:5601

  neo4j:
    image: 'neo4j'
    container_name: 'Neo4j'
    hostname: 'Neo4j'
    volumes:
      - neo4j:/data
    networks:
      - data_default
    ports:
      - 7474:7474
      - 7687:7687

  postgres:
    image: 'postgres'
    container_name: 'PostgreSQL'
    hostname: 'PostgreSQL'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres
    volumes:
       - postgres:/var/lib/postgresql/data
    networks:
      - data_default
    ports:
      - 5432:5432
  
  pgadmin:
    image: 'dpage/pgadmin4'
    container_name: 'pgAdmin'
    hostname: 'pgAdmin'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_PORT: 5050
    networks:
      - data_default
    ports:
      - 5050:80

networks:
  data_default:
    name: 'data_default'
    driver: 'bridge'

volumes:
  postgres:
  mongodb:
  neo4j:
  elasticsearch:
