version: '3.7'

services:
    postgres:
        image: 'postgres'
        container_name: 'PostgreSQL'
        hostname: 'PostgreSQL'
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: admin
            POSTGRES_DB: postgres
        volumes:
            - postgres:/var/lib/postgresql/data
        networks:
            - data_default
        ports:
            - 5432:5432

    mongo:
        image: 'mongo'
        container_name: 'MongoDB'
        hostname: 'MongoDB'
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
        volumes:
            - mongo:/data/db
        networks:
            - data_default
        ports:
            - 27017:27017
            - 27018:27018
            - 27019:27019

    elasticsearch:
        image: 'elasticsearch:7.5.1'
        container_name: 'ElasticSearch'
        hostname: 'ElasticSearch'
        environment:
            - discovery.type=single-node
        volumes:
            - elasticsearch:/usr/share/elasticsearch/data
        networks:
            - data_default
        ports:
            - 9200:9200
            - 9300:9300

    redis:
        image: 'bitnami/redis'
        container_name: 'Redis'
        hostname: 'Redis'
        environment:
            - ALLOW_EMPTY_PASSWORD=yes
        networks:
            - data_default
        ports:
            - 6379:6379

    neo4j:
        image: 'neo4j'
        container_name: 'Neo4j'
        hostname: 'Neo4j'
        environment:
            - NEO4J_AUTH=neo4j/admin
        volumes:
            - neo4j:/data
        networks:
            - data_default
        ports:
            - 7474:7474
            - 7687:7687

networks:
    data_default:
        name: 'data_default'
        driver: 'bridge'

volumes:
    postgres:
    mongo:
    elasticsearch:
    neo4j:
